### ISSUE TITLE
Process remains in SQL Server

### ISSUE THREAD

**Issue by eleite77** [ClearMeasure/AliaSQL#13]
When we execute it the process remains in the server so we have to kill it manually through the SQL Management console

**Comment by ericdc1** [comment]
I tested this out with a test project and can't seem to reproduce it. Can you give me some more info?

Here is a video of me testing this out against a bunch of scripts: http://screencast.com/t/0LqGLn0gCng

**Comment by eleite77** [comment]
thanks for your reply :-)

i put some code in my application_start because i want to check the db each time a user is accessing the platform

but the process lock the DB while it is on the task list in SQL Server 2014 Express edition
i can't for example drop the db or rename it. But can of course insert data, etc

i try to use the call in a using () {} statement but it is not possible as the object is not heriting IDispose

thanks for your help

**Comment by ericdc1** [comment]
Here is what I learned and came up with:

- If you call aliasql from the console the connections close when the process finishes running. 
- The aliasql dbupdater c# method is a very thin wrapper over the same code that the console app runs
- When calling dbupdater from a webapp, it leaves an open process in the SQL activity monitor that stays for a few minutes even though the query executor internally has all the connections inside using blocks

After seeing this in action I decided to make a simple database open and close in the web app the most overkill way possible:

            TestTable item;
            var sqlconnection = new SqlConnection(ConfigurationManager.ConnectionStrings["DemoConnectionString"].ConnectionString);
            using (sqlconnection)
            {
                sqlconnection.Open();
                item = sqlconnection.Query<TestTable>("select * from testtable where Id = @Id", new {Id = id}).FirstOrDefault();
                sqlconnection.Close();
                sqlconnection.Dispose();
            }
            return item;

With this, the connection still stays open in Activity Monitor for several minutes. 

It looks like this is by design due to connection pooling. https://msdn.microsoft.com/en-us/library/8xx3tyca(v=vs.80).aspx 

Calling this method after running dbUpdater or any other database connection via the web app frees the connections.   

      SqlConnection.ClearAllPools(); 

https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.clearallpools(v=vs.110).aspx
